sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "7.4.0"
  
before_install:
  - npm install -g --quiet  gulp-cli yo @angular/cli
  - npm link
